version: '3'

services:

  mysql:
    image: mysql:5.7.26
    privileged: false
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      # - ./conf/mysql/my.cnf:/etc/mysql/my.cnf
      - ./log/mysql/:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=typecho
      - MYSQL_USER=typecho
      - MYSQL_PASSWORD=123456
    networks:
      - backend

  # redis:
  #   image: redis
  #   privileged: false
  #   restart: always
  #   environment:
  #   - REDIS_PASS=**None**

  php:
    image: hteen/php
    volumes:
      - ./web:/www
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - frontend
      - backend

  nginx:
    image: nginx:1.16.0-alpine
    volumes:
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - ./log/nginx/:/var/log/nginx
      - ./web:/www
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 443:443
      - 80:80
    networks:
      - frontend

networks:
  frontend:
  backend: